### ISSUE TITLE
GridView columns shortcut declarations: allow value function as value 

### ISSUE THREAD

**Issue by robsch** [yiisoft/yii-dataview#6]
It would be nice if the columns could be defined this way:

```php
<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel'  => $searchModel,
    'columns'      => [
        // ---- current style ----
        [
            'attribute' => 'full_name',
            'label'     => 'Name',
            'format'    => 'html',
            'value'     => function (Order $model) {
                return Html::tag('span', $model->first_name . '<br>' . $model->last_name);
            },
        ],
        // ---- new alternative style ----
        'full_name:html:Name' => function(Order $model) {
            return Html::tag('span', $model->first_name . '<br>' . $model->last_name);
        },
        ...
        ['class' => 'yii\grid\ActionColumn'],
    ],
]); ?>
```
Would that be possible? Because of formatting I need to declare columns explicitly quite often. This would reduce the lines of code a bit.

**Comment by machour** [comment]
The builder sounds like an overkill to me. And a developer can already produce his own helpers, tailored for his needs easily anyway.

I really love the original proposal of @robsch regarding the short syntax, that I find more "Yii". 
It's clear, minimalistic and simple.

You can do either one of the following.

* provide a simple value that will be parsed:

```php
'columns' => [
  'contents:html:Post content',
]
```
* provide a `key` => `callback`

In this case, it's pretty straight forward that `callback` will return the value (in a key => value context)

```php
'columns' => [
  'contents:html:Post content' => function (Post $post) {
      return '<div>' . $post->contents . '</div>';
  },
]
```

* provide a `key` => `array`

The old way, that enabled to handle the `visible` prop on a DetailView.

We could do a minor enhancement and infer the attribute from the `key`, instead of requiring it in the array. 

```php
'columns' => [
  'contents' => [
    // 'attribute' => 'contents',
    // attribute is not required as we know it from the key. 
    // If attribute is present, then it overrides the key.
    'format' => 'html',
    'value' => function (Post $post) {
        return '<div>' . $post->contents . '</div>';
    },
   'visible' => function (...) {
   },
]
```

**Comment by samdark** [comment]
That is already in since columns are defined as an array of `ColumnInterface`.
